AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
Style/StringLiterals:
  EnforcedStyle: 'double_quotes'
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
